---
# 判断kube-apiserver、kube-controller-manager、kube-scheduler、kubectl是否安装
- name: To judge whether kube-apiserver install
  stat: path=/usr/local/bin/kube-apiserver
  changed_when: False
  register: kube_apiserver_result
  tags: [kubernetes-master]

- name: To judge whether kube-controller-manager install
  stat: path=/usr/local/bin/kube-controller-manager
  changed_when: False
  register: kube_controller_manager_result
  tags: [kubernetes-master]

- name: To judge whether kube-scheduler install
  stat: path=/usr/local/bin/kube-scheduler
  changed_when: False
  register: kube_scheduler_result
  tags: [kubernetes-master]

- name: To judge whether kubectl install
  stat: path=/usr/local/bin/kubectl
  changed_when: False
  register: kubectl_result
  tags: [kubernetes-master]

# 安装
- name: Install kube-apiserver
  copy: src=kube-apiserver dest=/usr/local/bin owner=root group=root mode=0755
  when: kube_apiserver_result.stat.exists == false
  tags: [kubernetes-master]

- name: Install kube-controller-manager
  copy: src=kube-controller-manager dest=/usr/local/bin owner=root group=root mode=0755
  when: kube_controller_manager_result.stat.exists == false
  tags: [kubernetes-master]

- name: Install kube-scheduler
  copy: src=kube-scheduler dest=/usr/local/bin owner=root group=root mode=0755
  when: kube_scheduler_result.stat.exists == false
  tags: [kubernetes-master]

- name: Install kubectl
  copy: src=kubectl dest=/usr/local/bin owner=root group=root mode=0755
  when: kubectl_result.stat.exists == false
  tags: [kubernetes-master]