---
# 用户和组相关变量
etcd_user_name: "etcd"
etcd_group_name: "etcd"
etcd_home_path: "/var/lib/etcd"


# etcd.conf相关变量
etcd_name: "master"
etcd_data_dir: "/var/lib/etcd/data"
etcd_config_dir: "/etc/etcd"
etcd_config_file: "etcd.conf"
etcd_ansible_groups_name: "etcd"
etcd_listen_client_urls: "http://{{ groups[etcd_ansible_groups_name][0] }}:2379"
etcd_advertise_client_urls: "http://{{ groups[etcd_ansible_groups_name][0] }}:2379"