---
- name: Deploy kubernetes slave
  hosts: nodes
  # become: yes
  # become_user: root
  # become_method: sudo
  remote_user: root
  gather_facts: true
  roles:
    - role: kubernetes-slave
  tags: [kubernetes-slave]