---

etcd_ansible_groups_name: "etcd"
masters_ansible_groups_name: "masters"

####################### etcd #######################
# 用户和组相关变量
etcd_user_name: "etcd"
etcd_group_name: "etcd"
etcd_home_path: "/var/lib/etcd"


# etcd.conf相关变量
etcd_name: "master"
etcd_data_dir: "/var/lib/etcd/data"
etcd_config_dir: "/etc/etcd"
etcd_config_file: "etcd.conf"
etcd_client_port: 2379
etcd_listen_client_urls: "http://{{ groups[etcd_ansible_groups_name][0] }}:{{ etcd_client_port }},http://127.0.0.1:{{ etcd_client_port }}"
etcd_advertise_client_urls: "http://{{ groups[etcd_ansible_groups_name][0] }}:{{ etcd_client_port }}"


####################### flannel #######################
flannel_etcd_url: "{{ etcd_advertise_client_urls }}"
flannel_etcd_key: "/kube-centos/network"
flannel_network: "172.20.0.0/16"
flannel_subnetlen: 24


####################### kubernetes #######################

# 用户和组相关
kube_user: "kube"

# 配置相关
kube_config_dir: "/etc/kubernetes"

kube_apiserver_config_file: "apiserver"
kube_controller_manager_config_file: "controller-manager"
kube_scheduler_config_file: "scheduler"

# 端口
kube_insecure_port: 8080
kube_secure_port: 6443
kubelet_port: 10250

# kube公用
kube_logtostderr: "--logtostderr=true"
kube_log_level: "--v=0"
kube_master: "--master=http://{{ groups[masters_ansible_groups_name][0] }}:{{ kube_insecure_port }}"
kube_allow_priv: "--allow-privileged=false"

# master公用
kube_service_account_file_name: "service_account_key.pem"

# apiserver
kube_etcd_servers: "--etcd-servers={{ etcd_advertise_client_urls }}"
kube_api_address: "--insecure-bind-address=0.0.0.0"
kube_api_port: "--insecure-port={{ kube_insecure_port }} --secure-port={{ kube_secure_port }}"
kube_node_port: "--kubelet-port={{ kubelet_port }}"
kube_advertise_addr: "--advertise-address={{ groups[masters_ansible_groups_name][0] }}"
kube_service_addresses: "--service-cluster-ip-range=10.0.0.0/24"
kube_admission_control: "--admission-control=NamespaceLifecycle, \
                        NamespaceExists,LimitRanger,SecurityContextDeny, \
                        ServiceAccount,ResourceQuota"
kube_api_client_ca_file: "--client-ca-file="
kube_api_tls_cert_file: "--tls-cert-file="
kube_api_tls_private_key_file: "--tls-private-key-file="
kube_api_service_account_key_file: "--service-account-key-file=\
                                    {{ kube_config_dir }}/{{ kube_service_account_file_name }}"

# controller-manager
kube_controller_manager_root_ca_file: "--root-ca-file="
kube_controller_manager_service_account_private_key_file: "--service-account-private-key-file=\
                                                          {{ kube_config_dir }}/{{ kube_service_account_file_name }}"

# scheduler
kube_scheduler_args: ""


# kubelet 和 kube-proxy
kubelet_config_file: "kubelet"
kube_proxy_config_file: "proxy"

# kube-slave 公用
kube_node_hostname: "--hostname-override="
kubelet_work_dir: "/var/lib/kubelet"
kube_node_address: "--address={{ ansible_default_ipv4.address }}"
# kubelet_api_server参数官方已经不推荐使用了，换成--kubeconfig
# kubelet_api_server: "--api-servers={{ groups[masters_ansible_groups_name][0] }}:{{ kube_insecure_port }}"
kubelet_api_server: ""
kubelet_pod_infra_container: "--pod-infra-container-image=docker.io/kubernetes/pause"
kubelet_args: "--kubeconfig={{ kubelet_work_dir }}/kubeconfig"

# kube-proxy
kube_proxy_args: "--kubeconfig={{ kubelet_work_dir }}/kubeconfig"